blueprint:
  name: Notify Dryer Complete (Binary Sensor)
  description: Send notification when the dryer cycle has completed
  domain: automation
  input:
    dryer_entity:
      name: Dryer Sensor
      selector:
        entity:
          domain: binary_sensor
    notification_service:
      name: Notification Service
      selector:
        target:
          entity:
            domain: script

max_exceeded: silent

trigger:
  platform: state
  entity_id: !input dryer_entity
  from: "on"
  to: "off"

action:
  - service: !input notification_service
    message: "Dryer cycle complete."
