blueprint:
  name: Notify Dryer Complete (Wattage)
  description: Send notification when the dryer cycle has completed by power usage
  domain: automation
  input:
    dryer_entity:
      name: Dryer Power Sensor
      selector:
        entity:
          domain: sensor
    min_dryer_reading:
      name: Minimum Dryer Power
      description: Minimum dryer power reading to consider off
      default: 60
      selector:
        number:
          min: 0
          max: 9999999
          unit_of_measurement: watts

    notification_service:
      name: Notification Service
      selector:
        target:
          entity:
            domain: script

max_exceeded: silent

trigger:
  platform: numeric_state
  entity_id: !input dryer_entity
  below: !input min_dryer_reading

action:
  - service: !input notification_service
    message: "Dryer cycle complete."
